2025-06-28 00:04:58,688 ERROR: Exception on /explore [GET] [in C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\Desktop\flask mega\app\routes.py", line 160, in explore
    per_page=app.confi['POSTS_PER_PAGE'],
             ^^^^^^^^^
AttributeError: 'Flask' object has no attribute 'confi'
2025-06-28 00:05:21,949 INFO: Microblog startup [in C:\Users\57671.DESKTOP-U9QCETA\Desktop\flask mega\app\__init__.py:44]
2025-06-28 00:21:57,139 INFO: Microblog startup [in C:\Users\57671.DESKTOP-U9QCETA\Desktop\flask mega\app\__init__.py:44]
2025-06-28 00:21:58,879 ERROR: Exception on / [GET] [in C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\Desktop\flask mega\app\routes.py", line 29, in index
    prev_url = url_for('index', page=posts.perv_num) if posts.has_perv else None
                                                        ^^^^^^^^^^^^^^
AttributeError: 'SelectPagination' object has no attribute 'has_perv'
2025-06-28 00:22:52,447 INFO: Microblog startup [in C:\Users\57671.DESKTOP-U9QCETA\Desktop\flask mega\app\__init__.py:44]
2025-06-28 00:29:42,546 INFO: Microblog startup [in C:\Users\57671.DESKTOP-U9QCETA\Desktop\flask mega\app\__init__.py:44]
2025-06-28 00:30:02,199 ERROR: Exception on /user/lynette [GET] [in C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\Desktop\flask mega\app\routes.py", line 85, in user
    query = user.posts.select().order_by(Post,timestamp.desc())
                                              ^^^^^^^^^
NameError: name 'timestamp' is not defined
2025-06-28 00:30:47,951 INFO: Microblog startup [in C:\Users\57671.DESKTOP-U9QCETA\Desktop\flask mega\app\__init__.py:44]
2025-06-28 00:30:54,095 ERROR: Exception on /user/lynette [GET] [in C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\Desktop\flask mega\app\routes.py", line 89, in user
    per_page=app.config['POST_PER_PAGE'],
             ~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'POST_PER_PAGE'
2025-06-28 00:31:21,004 INFO: Microblog startup [in C:\Users\57671.DESKTOP-U9QCETA\Desktop\flask mega\app\__init__.py:44]
2025-06-28 00:31:24,816 ERROR: Exception on /user/lynette [GET] [in C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\Desktop\flask mega\app\routes.py", line 89, in user
    per_page=app.config['POST_PER_PAGE'],
             ~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'POST_PER_PAGE'
2025-06-28 00:31:53,013 INFO: Microblog startup [in C:\Users\57671.DESKTOP-U9QCETA\Desktop\flask mega\app\__init__.py:44]
2025-06-28 00:34:17,650 INFO: Microblog startup [in C:\Users\57671.DESKTOP-U9QCETA\Desktop\flask mega\app\__init__.py:44]
2025-06-28 10:59:49,337 INFO: Microblog startup [in C:\Users\57671.DESKTOP-U9QCETA\Desktop\flask mega\app\__init__.py:46]
