2025-06-27 23:48:23,067 ERROR: Exception on /index [GET] [in C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\Desktop\flask mega\app\routes.py", line 22, in index
    return render_template(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\jinja2\environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\57671.DESKTOP-U9QCETA\Desktop\flask mega\app\templates\index.html", line 21, in template
    {{% include '_post.html' %}}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
2025-06-27 23:49:03,216 INFO: Microblog startup [in C:\Users\57671.DESKTOP-U9QCETA\Desktop\flask mega\app\__init__.py:44]
2025-06-27 23:49:10,465 ERROR: Exception on / [GET] [in C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\Desktop\flask mega\app\routes.py", line 22, in index
    return render_template(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\jinja2\environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\57671.DESKTOP-U9QCETA\Desktop\flask mega\app\templates\index.html", line 21, in template
    {{% include '_post.html' %}}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
2025-06-27 23:49:59,601 INFO: Microblog startup [in C:\Users\57671.DESKTOP-U9QCETA\Desktop\flask mega\app\__init__.py:44]
2025-06-28 00:03:13,537 INFO: Microblog startup [in C:\Users\57671.DESKTOP-U9QCETA\Desktop\flask mega\app\__init__.py:44]
2025-06-28 00:03:16,327 ERROR: Exception on / [GET] [in C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\Desktop\flask mega\app\routes.py", line 25, in index
    per_page=app.config['POST_PER_PAGE'],
             ~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'POST_PER_PAGE'
2025-06-28 00:04:41,421 INFO: Microblog startup [in C:\Users\57671.DESKTOP-U9QCETA\Desktop\flask mega\app\__init__.py:44]
