2025-07-01 02:33:34,549 ERROR: Exception on / [GET] [in C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2522, in get_property
    return self._props[key]
           ~~~~~~~~~~~^^^^^
KeyError: 'message_sent'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 915, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask\app.py", line 1291, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\Desktop\flask mega\app\routes.py", line 114, in before_request
    if current_user.is_authenticated:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\werkzeug\local.py", line 318, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\werkzeug\local.py", line 526, in _get_current_object
    return get_name(local())
                    ^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask_login\utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
                                      ^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask_login\utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\flask_login\login_manager.py", line 364, in _load_user
    user = self._user_callback(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\Desktop\flask mega\app\models.py", line 196, in load_user
    return db.session.get(User,int(id))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\orm\scoping.py", line 1058, in get
    return self._proxied.get(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 3694, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 3873, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\orm\loading.py", line 694, in load_on_pk_identity
    session.execute(
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\orm\context.py", line 306, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1415, in execute
    return meth(
           ^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1629, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
                                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 711, in _compile_w_cache
    compiled_sql = self._compiler(
                   ^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 320, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\sql\compiler.py", line 1446, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\sql\compiler.py", line 886, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\sql\compiler.py", line 932, in process
    return obj._compiler_dispatch(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\sql\visitors.py", line 141, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
           ^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\sql\compiler.py", line 4728, in visit_select
    compile_state = select_stmt._compile_state_factory(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\sql\base.py", line 687, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\orm\context.py", line 447, in create_for_statement
    return cls._create_orm_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\orm\context.py", line 1175, in _create_orm_context
    _QueryEntity.to_compile_state(
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\orm\context.py", line 2628, in to_compile_state
    _MapperEntity(
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\orm\context.py", line 2708, in __init__
    entity._post_inspect
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 1338, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2724, in _post_inspect
    self._check_configure()
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2401, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4214, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4255, in _do_configure_registries
    mapper._post_configure_properties()
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2418, in _post_configure_properties
    prop.init()
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\orm\interfaces.py", line 589, in init
    self.do_init()
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\orm\relationships.py", line 1661, in do_init
    self._generate_backref()
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\orm\relationships.py", line 2145, in _generate_backref
    self._add_reverse_property(self.back_populates)
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\orm\relationships.py", line 1592, in _add_reverse_property
    other = self.mapper.get_property(key, _configure_mappers=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\57671.DESKTOP-U9QCETA\desktop\flask mega\venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2524, in get_property
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Mapper 'Mapper[User(user)]' has no property 'message_sent'.  If this property was indicated from other mappers or configure events, ensure registry.configure() has been called.
2025-07-01 02:34:19,055 INFO: Microblog startup [in C:\Users\57671.DESKTOP-U9QCETA\Desktop\flask mega\app\__init__.py:62]
